server:
  port: 3000
spring:
  config:
    import:
      ./env-dev.yml
  flyway:
    enabled: true
    baseline-on-migrate: true
    user: ${DB_USER}
    password: ${DB_PASSWORD}
    baseline-description: "init"
    baseline-version: 0
  datasource:
    url: jdbc:postgresql://localhost:5430/desafiobossabox
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect